name: Build image and publish on ghcr

on:
  workflow_dispatch:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Get pflotran_ogs last commit hash
        run: |
          echo "SHORT_SHA=$(git ls-remote https://bitbucket.org/opengosim/pflotran_ogs_1.6.git HEAD | cut -f1 | cut -c 1-7)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
              ghcr.io/equinor/pflotran-ogs-docker:latest
              ghcr.io/equinor/pflotran-ogs-docker:${{ env.SHORT_SHA}}   
          build-args: |
              THREAD=2
